name: Terraform plan Difference
on:
  pull_request:
    branches:
      - master

jobs:
# Update 'Job name' and 'terraform_directory' as needed based on the module structure.
  complete-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-pr-checks.yaml@master
    with:
      provider: 'azurerm'
      terraform_directory: 'examples/complete'
      target_branch: 'master'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  
  key-vault-with-access-policy-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-pr-checks.yaml@master
    with:
      provider: 'azurerm'
      terraform_directory: 'examples/key_vault_with_access_policy'
      target_branch: 'master'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}