name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
# Update 'Job name' and 'working_directory' as needed based on the module structure.
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@88efd7724e007c8f721a219498be29e0c9ad471b
    with:
      working_directory: './examples/complete/'

  key-vault-with-access-policy-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@88efd7724e007c8f721a219498be29e0c9ad471b
    with:
      working_directory: 'examples/key_vault_with_access_policy/'
  
# Seperate Job for TFlint workflow call
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@88efd7724e007c8f721a219498be29e0c9ad471b
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
